name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd utils/dockerbuilds/CI/
        docker build . --file Dockerfile-base-2204-master --tag wesnoth:$(date +%s)
        ls
