FROM ubuntu:20.04

RUN apt update

RUN apt install -y -qq apt-utils

# boost
RUN apt install -y -qq libboost-filesystem-dev libboost-iostreams-dev libboost-locale-dev libboost-regex-dev libboost-program-options-dev libboost-random-dev libboost-system-dev libboost-coroutine-dev

# SDL
RUN apt install -y -qq libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev

# make tzdata not prompt for a timezone
ENV DEBIAN_FRONTEND=noninteractive

# misc
RUN apt install -y -qq libpng-dev libreadline6-dev libvorbis-dev libcairo2-dev libpango1.0-dev libbz2-dev zlib1g zlib1g-dev libpangocairo-1.0-0 libssl-dev  libcurl4-openssl-dev

# programs
RUN apt install -y -qq openssl bzip2 git cmake make gcc g++ lld doxygen gettext pigz

WORKDIR /home/wesnoth-travis
