FROM ubuntu:20.04

RUN apt update

RUN apt install -y -qq apt-utils

# boost
RUN apt install -y -qq libboost-filesystem1.74-dev libboost-iostreams1.74-dev libboost-locale1.74-dev libboost-regex1.74-dev libboost-program-options1.74-dev libboost-random1.74-dev libboost-system1.74-dev libboost-coroutine1.74-dev

# SDL
RUN apt install -y -qq libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev

# make tzdata not prompt for a timezone
ENV DEBIAN_FRONTEND=noninteractive

# misc
RUN apt install -y -qq libpng-dev libreadline6-dev libvorbis-dev libcairo2-dev libpango1.0-dev libbz2-dev zlib1g zlib1g-dev libpangocairo-1.0-0 libssl-dev  libcurl4-openssl-dev

# programs
RUN apt install -y -qq openssl bzip2 git cmake make gcc g++ lld doxygen gettext pigz

WORKDIR /home/wesnoth-travis
