name: Build x86_64 Packages

on:
  release:
  workflow_dispatch:

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:          
        include:
          - tool: cmake
            cc: gcc
            cxx: g++
            cfg: release
            lto: true
    runs-on: ubuntu-20.04
    container:
      image: alberic89/wesnoth-build-env:amd64
      options: "--tty --entrypoint /bin/bash" # docker create options
      env:
        TOOL: ${{ matrix.tool }}
        CFG: ${{ matrix.cfg }}
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
        CXX_STD: 17
        LTO: ${{ matrix.lto }}
        NLS: true
        CLICOLOR_FORCE: 1
        DISPLAY: :99.0
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      
      - name: Set Version env
        run: |
          echo "BFW_VERSION=$(echo 'import data.tools.wesnoth.version as v;print(v.as_string)' | python3)" >> $GITHUB_ENV
  
      - name: Build wesnoth
        id: build
        run: |
            cmake -DENABLE_GAME=true  \
              -DCMAKE_BUILD_TYPE="$CFG" -DCXX_STD="$CXX_STD" \
              -DEXTRA_FLAGS_CONFIG="-pipe" -DENABLE_STRICT_COMPILATION=true \
              -DENABLE_NLS="$NLS" -DFORCE_COLOR_OUTPUT=true -DENABLE_LTO="$LTO" -DLTO_JOBS=`nproc` .
            make VERBOSE=1 -j`nproc`
      
      - name: Install for build archive
        run: |
          make install DESTDIR=wesnoth-$BFW_VERSION -j`nproc`
      
      - name: Create Archive
        run: |
          tar -cvf wesnoth-$BFW_VERSION.tar.gz --use-compress-program=pigz wesnoth-$BFW_VERSION

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Wesnoth-${{env.BFW_VERSION}}.tar.gz
          path: |
            *.tar.gz
