name: Build Tar Packages

on:
  release:
  workflow_dispatch:
  workflow_run:
    workflows: [Docker Base Image CI]
    types:
      - completed

jobs:
  Build:
    if: |
      github.event.workflow_run.conclusion == 'success' || 
      github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:          
        include:
          - tool: cmake
            cc: gcc
            cxx: g++
            cfg: release
            lto: true
            arch: amd64
          - tool: cmake
            cc: gcc
            cxx: g++
            cfg: release
            lto: true
            arch: arm64
    runs-on: ubuntu-20.04
    env:
      TOOL: ${{ matrix.tool }}
      CFG: ${{ matrix.cfg }}
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      CXX_STD: 17
      LTO: ${{ matrix.lto }}
      NLS: true
      CLICOLOR_FORCE: 1
      DISPLAY: :99.0
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set up QEMU
        if: ${{ matrix.arch == 'arm64' }}
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set Version env
        run: |
          echo "BFW_VERSION=$(echo 'import data.tools.wesnoth.version as v;print(v.as_string)' | python3)" >> $GITHUB_ENV
  
      - name: Build wesnoth
        run: |
          echo 'cmake -DENABLE_GAME=true -DCMAKE_BUILD_TYPE="$CFG" -DCXX_STD="$CXX_STD" -DEXTRA_FLAGS_CONFIG="-pipe" -DENABLE_STRICT_COMPILATION=true -DENABLE_NLS="$NLS" -DFORCE_COLOR_OUTPUT=true -DENABLE_LTO="$LTO" -DLTO_JOBS=`nproc` . && make -j`nproc` && make install DESTDIR=/home/wesnoth-travis/wesnoth/wesnoth-build -j`nproc`' > build.sh
          podman run --env-host -v=`pwd`:/home/wesnoth-travis/wesnoth docker.io/alberic89/wesnoth-ci:${{ matrix.arch }}-ubuntu-20.04 /bin/sh /home/wesnoth-travis/wesnoth/build.sh
      
      - name: Create Archive
        run: |
          apt update && apt install -y -qq pigz
          tar -cvf wesnoth-$BFW_VERSION-${{ matrix.arch }}.tar.gz --use-compress-program=pigz wesnoth-build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Wesnoth-${{env.BFW_VERSION}}-ubuntu20.04-${{ matrix.arch }}.tar.gz
          path: |
            *.tar.gz
