name: Build x86_64 Packages

on:
  release:
  workflow_dispatch:

jobs:
  Packages_x86_64_Build:
    strategy:
      fail-fast: false
      matrix:          
        include:
          - tool: cmake
            cc: gcc
            cxx: g++
            cfg: release
            lto: true
    runs-on: ubuntu-20.04
    container:
      image: wesnoth/wesnoth:2204-master
      options: "--tty --entrypoint /bin/bash" # docker create options
      env:
        TOOL: ${{ matrix.tool }}
        CFG: ${{ matrix.cfg }}
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
        CXX_STD: 17
        LTO: ${{ matrix.lto }}
        NLS: false
        CLICOLOR_FORCE: 1
        DISPLAY: :99.0
        ARCH: x86_64
        ARCH_NAME: amd64
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      
      - name: Set Version env
        run: |
          echo "BFW_VERSION=$(echo 'import data.tools.wesnoth.version as v;print(v.as_string)' | python3)" >> $GITHUB_ENV
          echo ${{ env.BFW_VERSION }}
  
      - name: Build wesnoth
        id: build
        run: |
            cmake -DENABLE_GAME=true  \
              -DCMAKE_BUILD_TYPE="$CFG" -DCXX_STD="$CXX_STD" -DCMAKE_INSTALL_PREFIX=/usr \
              -DEXTRA_FLAGS_CONFIG="-pipe" -DENABLE_STRICT_COMPILATION=true -DENABLE_MYSQL=true \
              -DENABLE_NLS="$NLS" -DFORCE_COLOR_OUTPUT=true -DENABLE_LTO="$LTO" -DLTO_JOBS=`nproc` .
            make VERBOSE=1 -j`nproc`
      
      - name: Install in AppDir
        run: |
          make install DESTDIR=AppDir -j`nproc`
      
      - name: Build x86_64 AppImage
        continue-on-error: true
        run: |
          apt-get update && apt-get install -y binutils coreutils desktop-file-utils fakeroot fuse libgdk-pixbuf2.0-dev patchelf python3-pip python3-setuptools squashfs-tools strace util-linux zsync pigz
          pip3 install appimage-builder
          appimage-builder --skip-tests
 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Wesnoth-${{env.BFW_VERSION}}.AppImage
          path: |
            *.AppImage
      
      - name: Re-use cmake
        run: |
          cmake -DENABLE_GAME=true  \
              -DCMAKE_BUILD_TYPE="$CFG" -DCXX_STD="$CXX_STD" -DCMAKE_INSTALL_PREFIX=.local/ \
              -DEXTRA_FLAGS_CONFIG="-pipe" -DENABLE_STRICT_COMPILATION=true -DENABLE_MYSQL=true \
              -DENABLE_NLS="$NLS" -DFORCE_COLOR_OUTPUT=true -DENABLE_LTO="$LTO" -DLTO_JOBS=`nproc` .
      
      - name: Install for build archive
        run: |
          make install DESTDIR=wesnoth-$BFW_VERSION -j`nproc`
      
      - name: Create Archive
        continue-on-error: true
        run: |
          tar -cvf wesnoth-$BFW_VERSION.tar.gz --use-compress-program=pigz wesnoth-$BFW_VERSION/__w/wesnoth/wesnoth/.local

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Wesnoth-${{env.BFW_VERSION}}.tar.gz
          path: |
            *.tar.gz
