name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ubuntu-2004:
    strategy:
      fail-fast: false
      matrix:
        include:
          - tool: cmake
            cc: clang
            cxx: clang++
            cfg: debug
            lto: false
    runs-on: ubuntu-20.04
    container:
      image: wesnoth/wesnoth:2204-master
      options: --tty # docker create options
      env:
        TOOL: ${{ matrix.tool }}
        CFG: ${{ matrix.cfg }}
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
        CXX_STD: 17
        LTO: ${{ matrix.lto }}
        NLS: false
        CLICOLOR_FORCE: 1
        DISPLAY: :99.0
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Build wesnoth, wesnothd, campaignd and unit tests
        id: build # needed to check step outcome
        run: |
          case $TOOL in
            scons)
              scons wesnoth wesnothd campaignd boost_unit_tests \
                build="$CFG" ctool="$CC" cxxtool="$CXX" cxx_std="$CXX_STD" \
                extra_flags_config="-pipe" strict=true forum_user_handler=true \
                nls="$NLS" enable_lto="$LTO" force_color=true jobs=2 --debug=time
              ;;
            cmake)
              cmake -DENABLE_GAME=true -DENABLE_SERVER=true -DENABLE_CAMPAIGN_SERVER=true \
                -DENABLE_TESTS=true -DCMAKE_BUILD_TYPE="$CFG" -DCXX_STD="$CXX_STD" \
                -DEXTRA_FLAGS_CONFIG="-pipe" -DENABLE_STRICT_COMPILATION=true -DENABLE_MYSQL=true \
                -DENABLE_NLS="$NLS" -DFORCE_COLOR_OUTPUT=true -DENABLE_LTO="$LTO" -DLTO_JOBS=2 .
              make conftests
              make VERBOSE=1 -j2
              ;;
          esac
