name: Docker Image Build

on:
  workflow_dispatch:

env:
  REGISTRY_USER: alberic89
  IMAGE_REGISTRY: docker.io
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0

    - name: Log in to Docker.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}
    
    - name: Build the Docker Image
      run: |
        podman build . --file Dockerfile --rm --tag docker.io/alberic89/wesnoth:latest --platform linux/amd64 --platform linux/arm64
   
    - name: Push the Docker Image
      run: |
        podman push docker.io/alberic89/wesnoth:latest
