name: Docker Image Build

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build Tar Packages]
    types:
      - requested

env:
  REGISTRY_USER: alberic89
  IMAGE_REGISTRY: docker.io
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  build:
    strategy:
      matrix:
        include: 
          - arch: arm64
          - arch: amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: "recursive"

    - name: Set up QEMU
      if: ${{ matrix.arch == 'arm64' }}
      uses: docker/setup-qemu-action@v2.1.0

    - name: Log in to Docker.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}
    
    - name: Build the Docker Image
      run: |
        podman build . --file Dockerfile --rm --tag wesnoth:${{ matrix.arch }} --build-arg ARCH=${{ matrix.arch }} --build-arg BFW_VERSION=$(echo 'import data.tools.wesnoth.version as v;print(v.as_string)' | python3) --platform=linux/${{ matrix.arch }} --jobs=`nproc`
   
    - name: Push the Docker Image
      run: |
        podman push localhost/wesnoth:${{ matrix.arch }} docker.io/alberic89/wesnoth:${{ matrix.arch }}
